It throws java.lang.NoSuchMethodError when writing to hive ORC table: ``` Caused by: java.lang.NoSuchMethodError: org.apache.orc.TypeDescription.createRowBatch(I)Lorg/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch;   at org.apache.hadoop.hive.ql.io.orc.WriterImpl.<init>(WriterImpl.java:96)   at org.apache.hadoop.hive.ql.io.orc.OrcFile.createWriter(OrcFile.java:320)   at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat$OrcRecordWriter.write(OrcOutputFormat.java:103)   at org.apache.spark.sql.hive.execution.HiveOutputWriter.write(HiveFileFormat.scala:150)   at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.write(FileFormatDataWriter.scala:137)   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:242)   at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1351)   at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:239) ```
https://github.com/apache/hive/blob/release-1.2.1/ql/src/java/org/apache/hadoop/hive/ql/io/orc/WriterImpl.java
https://github.com/apache/hive/blob/rel/release-2.3.4/ql/src/java/org/apache/hadoop/hive/ql/io/orc/WriterImpl.java#L88
https://github.com/apache/hive/blob/rel/release-2.3.4/storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch.java